<?php
/**
 * Plugin Name: RSS Feed Icon
 * Plugin URI: https://github.com/ArthurGareginyan/rss-feed-icon
 * Description: This plugin allows you to easily add RSS feed icon in any place on your website.
 * Author: Arthur Gareginyan
 * Author URI: http://www.arthurgareginyan.com
 * Version: 1.0
 * License: GPL3
 * Text Domain: rss-feed-icon
 * Domain Path: /languages/
 *
 * Copyright 2014-2016 Arthur Gareginyan (email : arthurgareginyan@gmail.com)
 *
 * This file is part of "RSS Feed Icon".
 *
 * "RSS Feed Icon" is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * "RSS Feed Icon" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with "RSS Feed Icon".  If not, see <http://www.gnu.org/licenses/>.
 *
 */


/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Define global constants
 *
 * @since 1.0
 */
defined('RSSFI_DIR') or define('RSSFI_DIR', dirname(plugin_basename(__FILE__)));
defined('RSSFI_BASE') or define('RSSFI_BASE', plugin_basename(__FILE__));
defined('RSSFI_URL') or define('RSSFI_URL', plugin_dir_url(__FILE__));
defined('RSSFI_PATH') or define('RSSFI_PATH', plugin_dir_path(__FILE__));
defined('RSSFI_TEXT') or define('RSSFI_TEXT', 'rss-feed-icon');
defined('RSSFI_VERSION') or define('RSSFI_VERSION', '1.0');

/**
 * Register text domain
 *
 * @since 0.1
 */
function RssFeedIcon_textdomain() {
	load_plugin_textdomain( RSSFI_TEXT, false, RSSFI_DIR . '/languages/' );
}
add_action( 'init', 'RssFeedIcon_textdomain' );

/**
 * Print direct link to RssFeedIcon admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the SpecificFeeds admin page
 *
 * @since  0.1
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function RssFeedIcon_settings_link( $links ) {
	$settings_page = '<a href="' . admin_url( 'options-general.php?page=rss-feed-icon.php' ) .'">' . __( 'Settings', RSSFI_TEXT ) . '</a>';
	array_unshift( $links, $settings_page );
	return $links;
}
add_filter( 'plugin_action_links_'.RSSFI_BASE, 'RssFeedIcon_settings_link' );

/**
 * Register submenu in "Settings" Admin Menu
 *
 * @since 0.1
 */
function RssFeedIcon_menu() {
	add_options_page('RSS Feed Icon', 'RSS Feed Icon', 'manage_options', 'rss-feed-icon', 'RssFeedIcon_render_submenu_page');
}
add_action( 'admin_menu', 'RssFeedIcon_menu' );

/**
 * Attach Settings Page
 *
 * @since 0.1
 */
require_once( RSSFI_PATH . 'inc/php/settings_page.php' );

/**
 * Load scripts and style sheet for settings page
 *
 * @since 1.0
 */
function RssFeedIcon_load_scripts($hook) {

    // Return if the page is not a settings page of this plugin
    if ( 'settings_page_rss-feed-icon' != $hook ) {
        return;
    }

    // WordPress library
    wp_enqueue_media();
    
    // Style sheet
    wp_enqueue_style( 'specificfeedsicon-admin-css', RSSFI_URL . 'inc/css/admin.css' );

    // JavaScript
    wp_enqueue_script( 'specificfeedsicon-admin-js', RSSFI_URL . 'inc/js/admin.js', array(), false, true );

}
add_action( 'admin_enqueue_scripts', 'RssFeedIcon_load_scripts' );

/**
 * Register settings
 *
 * @since 0.1
 */
function RssFeedIcon_register_settings() {
	register_setting( 'RssFeedIcon_settings_group', 'RssFeedIcon_settings' );
}
add_action( 'admin_init', 'RssFeedIcon_register_settings' );

/**
 * Image Uploader
 *
 * @since 1.0
 */
function RssFeedIcon_image_uploader( $name, $width, $height, $options ) {

    // Set variables
    $default_image = plugins_url('inc/img/no-image.png', __FILE__);

    if ( !empty( $options[$name] ) ) {
        $image_attributes = wp_get_attachment_image_src( $options[$name], array( $width, $height ) );
        $src = $image_attributes[0];
        $value = $options[$name];
    } else {
        $src = $default_image;
        $value = '';
    }

    $text = __( 'Upload', RSSFI_TEXT );

    // Print HTML field
    echo '
        <div class="upload">
            <img data-src="' . $default_image . '" src="' . $src . '" width="' . $width . 'px" height="' . $height . 'px" />
            <div>
                <input type="hidden" name="RssFeedIcon_settings[' . $name . ']" id="RssFeedIcon_settings[' . $name . ']" value="' . $value . '" />
                <button type="submit" class="upload_image_button button">' . $text . '</button>
                <button type="submit" class="remove_image_button button">&times;</button>
            </div>
        </div>
    ';
}

/**
 * ShortCode
 *
 * @since 1.0
 */
function RssFeedIcon_shortcode() {

    // Set variables
    $options = get_option( 'RssFeedIcon_settings' );

    if ( !empty( $options['feed_link'] ) ) {
        $feed_link = $options['feed_link'];
    } else {
        $feed_link = '/?feed=rss';
    }

    if ( !empty( $options['custom_icon'] ) ) {
        $image_attributes = wp_get_attachment_image_src( $options['custom_icon'] );
        $src = $image_attributes[0];
    } else {
        if ( !empty( $options['integrated_icon'] ) ) {
            $src = plugins_url( 'inc/img/icons/' . $options['integrated_icon'] . '.png', __FILE__ );
        } else {
            $src = plugins_url( 'inc/img/icons/8.png', __FILE__ );
        }
    }

    if ( !empty( $options['icon_size'] ) ) {
        $icon_size = $options['icon_size'];
    } else {
        $icon_size = '60';
    }

	// Generating output code
	return '<a
				href="' . $feed_link . '"
				target="_blank"
				rel="nofollow"
                style="text-decoration: none;"
    		>
    		<img
    			src="' . $src . '"
    			height="' . $icon_size . '"
                title="RSS Feed"
    			style="border: none;"
    		/>
    		</a>';
}
add_shortcode( 'rss-feed-icon', 'RssFeedIcon_shortcode' );

/**
 * Allow shortcodes in the text widget
 *
 * @since 1.0
 */
add_filter('widget_text', 'do_shortcode');

/**
 * Delete Options on Uninstall
 *
 * @since 0.1
 */
function RssFeedIcon_uninstall() {
	delete_option( 'RssFeedIcon_settings' );
}
register_uninstall_hook( __FILE__, 'RssFeedIcon_uninstall' );

?>